---
name: Run tests

on:
  push:
    branches: [mainline eql]
  pull_request:
    branches: [mainline]

jobs:
  build-clj:
    strategy:
      matrix:
        jdk: [17]
        clojure: [11]

    name: Clojure ${{ matrix.clojure }} (Java ${{ matrix.jdk }})

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Java ${{ matrix.jdk }}
        uses: actions/setup-java@v2.5.0
        with:
          distribution: zulu
          java-version: ${{ matrix.jdk }}
          cache: maven
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest
      - name: Run xtdb-eql tests
        run: clojure -X:dev:test:run-tests :xtdb-eql --reporter documentation

      - name: Run datalevin-eql tests
        run: clojure -M:dev:test:run-tests :datalevin-eql --reporter documentation

      - name: Run fulcro-eql tests
        run: clojure -M:dev:test:run-tests :fulcro-eql --reporter documentation

      - name: Run core tests
        run: clojure -M:dev:test:run-tests :core --reporter documentation


  build-cljs:
    name: ClojureScript

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java 11
        uses: actions/setup-java@v2.5.0
        with:
          distribution: zulu
          java-version: 11
          cache: maven
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest
      - name: Setup Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install
      - name: Compile tests
        run: yarn shadow-cljs compile ci-tests
      - name: Run tests
        run: ./node_modules/.bin/karma start --single-run
